#!/usr/bin/env bash
# Jordan huang<good5dog5@gmail.com>

set -o errexit
set -o pipefail
set -o nounset



is_command() {
    command -v "$1" > /dev/null 2>&1
}
system_type=$(uname -s)
packages=" vim tmux git zsh ranger "

cd "$HOME"

echo "Initialising submodules"
yadm submodule update --recursive --init

if [ ${system_type} = "Linux" ]; then
    if  is_command sudo; then
        sudo apt-get update -y && sudo apt-get install ${packages} -y
        # install oh-my-zsh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        sudo chsh -s $(which zsh)
    else
        apt-get update -y && apt-get install ${packages} -y
        # install oh-my-zsh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        chsh -s $(which zsh)
    fi
fi

if [ ${system_type} = "Darwin" ]; then
    if ! is_command zsh; then
        echo "Installing zsh..."
        brew install zsh
        if [ $? -eq 0 ]; then
            echo "All packages are installed."
        else
            echo "Install zsh error."
        fi
    fi
fi

