BASEDIR     :=$(shell pwd)
CHEWING_DIR :=${HOME}/.chewing
all:
	@test -d ${CHEWING_DIR} || mkdir 		  ${CHEWING_DIR} 
	cp       ${BASEDIR}/uhash.dat             ${CHEWING_DIR}
	cp       ${BASEDIR}/xprofile              ${HOME}/.xprofile
