# Somesier navigation 
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias dc="cd ~/Documents"

# Fast edit config file
alias evr="vim $HOME/.vimrc"
alias ebr="vim $HOME/.bashrc"
alias sbr="source $HOME/.bashrc"
alias eba="vim $HOME/.bash_aliases"
alias etmr="vim $HOME/.tmux.conf"

#Shortcuts
alias h="history | tail -100"

alias ll="ls -alhF --color=auto"
#list hidden files
alias l.="ls -d .*"
#list directories
alias lld="ls -lUd */ --color=auto"  
alias ls="ls --color=auto  --group-directories-first --sort=extension"
alias grep="grep -n --color=auto"
#word grep
alias wg="grep -inR --color=auto"
#find name
alias fn="find ./ -iname "
alias dic="sdcv"
alias opend="xdg-open"

# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"
 
#Aliases toward tmux
alias tmux="tmux -2"
alias tml="tmux list-sessions"
alias tma="tmux attach-session -t"
alias tmc="clear && tmux clear-history"
alias tmk="tmux kill-session -t"

#Make mount output human readable
alias mount='mount |column -t'
#Network relative
alias inet='ifconfig | grep "inet addr"'
alias ports='netstat -tulanp'

alias telnet_ptt="luit -encoding big5 telnet ptt.cc"
alias vi="vim"
alias py="python"

#For delelopment convinient

alias armgcc="arm-linux-gnueabihf-gcc"
alias armobjdump="arm-linux-gnueabihf-objdump"
alias gdb="gdb -q"

#For git
alias gst='git status '
alias gstuno='git status -uno'
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gl='git log'

alias js="java -jar /home/jordan/.local/bin/js.jar"

# Functions ------------------
md () { mkdir -p "$1" && cd "$1"; } #mkdir and go to new dir 
#bu - Back Up a file. Usage "bu filename.txt" 
bu () { cp $1 ${1}-`date +%Y%m%d%H%M`.backup ; }
mm() { 

    if [ -e "Makefile.ELX" ];
    then
        colormake -f Makefile.ELX $1
    else 
        colormake $1
fi
}
mc() {

    if [ -e "Makefile.ELX" ];
    then
        colormake -f Makefile.ELX clean && colormake -f Makefile.ELX $1
    else
        colormake clean && colormake $1
    fi
}
jserv () {
    if [ -d "$HOME/Dropbox/EDIMAX" ];
    then
        cd $HOME/Dropbox/EDIMAX && jekyll serve 
    fi
}
