#Get python version

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Set the default editor
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/usr/script
export PATH=$PATH:$HOME/usr/nand2tetris/tools
export PATH=$PATH:$HOME/usr/phantomjs/bin

#export CLASSPATH="$HOME.local/bin/js.jar"
export EDITOR=vim

#Some path for daily use
export STARDICT_DATA_DIR=$HOME/stardict/dic/
export UVA_PATH=$HOME/github/codeSet/c/Uva/

#Get color support for 'less'
export LESS="--RAW-CONTROL-CHARS"

export NVM_DIR="/home/jordan/.nvm"
export DOTFILE="${HOME}/github/dotfile"

_source_files()
{
    [ ! $# -eq 1 ] &&  return

    if [ ! -e "${1}" ]; then 
        # echo "${1} doesn't exist"
        return
    fi

    # -s : True if FILE exists and has a size greater than zero.
    [ -f "${1}" ] && source "${1}" && return

    local files="${1}/*"
    for f in $files
    do
        . "${f}"
    done
}
# Source all alias files
_source_files "${HOME}/bash_conf"

# Source all auto_complete files
_source_files "$DOTFILE/script/autoComplete"
_source_files "/etc/default/locale"
_source_files "/etc/bash_completion"

# Source Powerline to enable bash prompt
_source_files "/usr/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh" 
_source_files "${HOME}/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh"

# Source to enable Autojump
_source_files "/usr/share/autojump/autojump.bash"

# Source to enable bashmarks
_source_files "${HOME}/.local/bin/bashmarks.sh"

# Use colors for less, man, etc.
_source_files "${HOME}/.LESS_TERMCAP"

# Load nvm
_source_files "$NVM_DIR/nvm.sh"

# Set the PS1 prompt (with color).
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\][ \W ]\[\033[00m\]\$ '


# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
shopt -s histverify

# Enable Ctrl-z to toggle vim fg-bg switch
# remap susp to ^o and ~/.inputrc assing ^z to "fg
stty susp ^o


