# Somesier navigation 
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias dc="cd ~/Documents"

# Fast edit config file
alias evr="vim $HOME/.vimrc"
alias ebr="vim $HOME/.bashrc"
alias sbr="source $HOME/.bashrc"
alias eba="vim $HOME/.bash_aliases"
alias etmr="vim $HOME/.tmux.conf"

#Shortcuts
alias h="history | tail -100"

# ls -r mean reverse the sort order
alias ll="ls -alrhF --color=auto --group-directories-first"
#list hidden files
alias l.="ls -d .*"
#list directories
alias lld="ls -lrUd */ --color=auto"  
alias ls="ls -r --color=auto  --group-directories-first --sort=extension"
alias grep="grep  --color=auto"
#word grep
alias wg="grep -inR --color=auto"
#find name
alias fn="find ./ -iname "
alias dic="sdcv"
alias opend="xdg-open"

# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"
 
#Aliases toward tmux
alias tmux="tmux -2"
alias tml="tmux list-sessions"
alias tma="tmux attach-session -t"
alias tmc="clear && tmux clear-history"
alias tmk="tmux kill-session -t"

#Make mount output human readable
alias mount='mount |column -t'
#Network relative
alias inet='ifconfig | grep "inet addr"'
alias ports='netstat -tulanp'

alias telnet_ptt="luit -encoding big5 telnet ptt.cc"
alias vi="vim"
alias py="python"

#For delelopment convinient

alias armgcc="arm-linux-gnueabihf-gcc"
alias armobjdump="arm-linux-gnueabihf-objdump"
alias gdb="gdb -q"

#For git
alias gst='git status '
alias gstuno='git status -uno'
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gl='git log'

alias js="java -jar /home/jordan/.local/bin/js.jar"
alias netok="ping 8.8.8.8"

# Functions ------------------
md () { mkdir -p "$1" && cd "$1"; } #mkdir and go to new dir 
#bu - Back Up a file. Usage "bu filename.txt" 
bu () { cp $1 ${1}-`date +%Y%m%d%H%M`.backup ; }

# MAKE 
#-------------------------------------
makefile=""
make=""

chkEnv() {
    # Determine make and makefile

    if [ -e "Makefile.ELX" ];
    then
        makefile="Makefile.ELX"
    else
        makefile="Makefile"
    fi
    if [ "${PWD##/home/jordan/Documents/Edimax/ELX/boards}" != "${PWD}" ];
    then 
        make="make"
    else
        make="colormake"
    fi
    echo $makefile
    echo $make
}

# Make 
mm() { 
    chkEnv
    $make -f $makefile $1
}
# make clear
mc() {

    chkEnv
    $make -f $makefile clean
}
# Clear then make all
cm() {
    chkEnv
    $make -f $makefile clean && $make -f $makefile $1
}
# make -f makefile menuconfig
mmu() {
    if [ "${PWD##/home/jordan/Documents/Edimax/ELX/boards}" != "${PWD}" ];
    then
        make -f Makefile.ELX menuconfig
    else
        echo "Please eba"
    fi
}
jserv () {
    if [ -d "$HOME/Dropbox/EDIMAX" ];
    then
        cd $HOME/Dropbox/EDIMAX && jekyll serve 
    fi
}
uva() {
    cd "$HOME/github/codeSet/c/Uva/"
    mkdir -p "$1" && cd "$1"
    cp "$HOME/.vim/template/template.c" "./$1.c"

    if [ -f "../Makefile" ];
    then
        ln -sf "../Makefile" "./Makefile"
    fi
}
