ranger_dir:=${XDG_CONFIG_HOME}/test
linkfile:="rc.conf    \
		  rifle.conf \
		  scope.sh"
all: ranger

ranger: 
	@test -d ${ranger_dir} || mkdir ${ranger_dir}
	for file in ${linkfile}; do  			     \
		echo "${linkfile}"                       \
    done 										 \
	# @ln -sfr ./rc.conf ${ranger_dir}/rc.conf
	# ln -sfr ./${file}  ${ranger_dir}/${file} \
